apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      containers:
      - name: myapp-container1
        image: "${DOCKER_USERNAME}/${IMAGE_NAME}:latest"
        ports:
        - containerPort: 8000
