apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp3
  template:
    metadata:
      labels:
        app: myapp3
    spec:
      containers:
      - name: myapp-container3
        image: "ranatarek/my1image:latest"
        ports:
        - containerPort: 8000
