apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp2
  template:
    metadata:
      labels:
        app: myapp2
    spec:
      containers:
      - name: myapp-container2
        image: "ranatarek/pipline_docker_image28:latest"
        ports:
        - containerPort: 8000
